# Generated by Django 2.1.2 on 2018-10-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SottoGenere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sottogeneri',
            },
        ),
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='editore',
            options={'verbose_name_plural': 'Editori'},
        ),
        migrations.AlterModelOptions(
            name='genere',
            options={'verbose_name_plural': 'Generi'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titolo'], 'verbose_name_plural': 'Libri'},
        ),
        migrations.AlterField(
            model_name='libro',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genere',
        ),
        migrations.AddField(
            model_name='libro',
            name='genere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Genere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sottogenere',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genere'),
        ),
        migrations.AddField(
            model_name='libro',
            name='sottogenere',
            field=models.ManyToManyField(blank=True, to='core.SottoGenere'),
        ),
    ]
