# Generated by Django 2.1.2 on 2018-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181030_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sottogenere',
            field=models.ManyToManyField(to='core.SottoGenere'),
        ),
    ]
