# Generated by Django 2.1.2 on 2018-10-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181030_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='sottogenere',
            new_name='sottogeneri',
        ),
    ]
