# Generated by Django 2.1.2 on 2018-11-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181031_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('editore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Editore')),
            ],
            options={
                'verbose_name_plural': 'Collane',
            },
        ),
        migrations.AlterField(
            model_name='libro',
            name='collana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Collana'),
        ),
    ]
