# Generated by Django 2.1.2 on 2018-11-05 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20181105_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Libro')),
            ],
            options={
                'ordering': ['-data'],
                'verbose_name_plural': 'Prestiti',
            },
        ),
        migrations.CreateModel(
            name='Profilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfisc', models.CharField(max_length=11, verbose_name='Codice fiscale')),
                ('data_nascita', models.DateField(verbose_name='Data di nascita')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RichiestaPrestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('PN', 'Pendente'), ('AC', 'Accettata'), ('RF', 'Rifiutata')], max_length=2)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Libro')),
                ('profilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profilo')),
            ],
            options={
                'ordering': ['-data_richiesta'],
                'verbose_name_plural': 'Richiesta Prestiti',
            },
        ),
        migrations.AddField(
            model_name='prestito',
            name='profilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profilo'),
        ),
    ]
