# Generated by Django 2.1.2 on 2018-11-06 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profilo_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestito',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestito',
            name='profilo',
        ),
        migrations.RemoveField(
            model_name='richiestaprestito',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='richiestaprestito',
            name='profilo',
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titolo'], 'permissions': (('view_dettaglio_libro', 'Accesso al dettaglio di un libro'),), 'verbose_name_plural': 'Libri'},
        ),
        migrations.AlterModelOptions(
            name='profilo',
            options={'verbose_name_plural': 'Profili'},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='disponibile',
        ),
        migrations.AddField(
            model_name='libro',
            name='data_prestito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='data_richiesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='profilo_prestito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Profilo'),
        ),
        migrations.AddField(
            model_name='libro',
            name='stato_prestito',
            field=models.CharField(choices=[('PN', 'Pendente'), ('PR', 'In prestito'), ('DS', 'Disponibile')], default='DS', max_length=2),
        ),
        migrations.AddField(
            model_name='profilo',
            name='cognome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilo',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Prestito',
        ),
        migrations.DeleteModel(
            name='RichiestaPrestito',
        ),
    ]
