# Generated by Django 2.1.2 on 2018-11-08 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181107_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titolo'], 'permissions': (('view_dettaglio_libro', 'Accesso al dettaglio di un libro'), ('gestisci_prestito', 'Accetta o rifiuta richieste di prestito')), 'verbose_name_plural': 'Libri'},
        ),
        migrations.AddField(
            model_name='profilo',
            name='prestito_sospeso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilo',
            name='tot_libri',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterUniqueTogether(
            name='profilo',
            unique_together={('nome', 'cognome', 'codfisc')},
        ),
    ]
