# Generated by Django 2.1.2 on 2018-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181109_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titolo'], 'permissions': (('view_dettaglio_libro', 'Accesso al dettaglio di un libro'), ('gestisci_prestito', 'Gestione richieste e prestiti')), 'verbose_name_plural': 'Libri'},
        ),
        migrations.AddField(
            model_name='profilo',
            name='data_fine_sospensione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilo',
            name='data_inizio_sospensione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='tipo',
            field=models.CharField(choices=[('D', 'Danneggiamento'), ('R', 'Ritardo consegna'), ('A', 'Altro')], max_length=10),
        ),
    ]
