# Generated by Django 2.1.3 on 2018-11-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('RC', 'Richiesto'), ('IC', 'In corso')], max_length=2)),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('data_prestito', models.DateField(blank=True, null=True)),
                ('data_restituzione', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='data_prestito',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='data_restituzione',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='data_richiesta',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='profilo_prestito',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='stato_prestito',
        ),
        migrations.AddField(
            model_name='prestito',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Libro'),
        ),
        migrations.AddField(
            model_name='prestito',
            name='profilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profilo'),
        ),
        migrations.AlterUniqueTogether(
            name='prestito',
            unique_together={('profilo', 'libro')},
        ),
    ]
