# Generated by Django 2.1.2 on 2018-11-12 17:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181112_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'permissions': (('view_dettaglio_documento', 'Accesso al dettaglio del documento'),), 'verbose_name_plural': 'Documenti'},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='args',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='kwargs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='urlname',
            field=models.CharField(default=78, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='urlparams',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(help_text='Dimensione massima: 50 Kb', upload_to='documenti/%Y/%m/', validators=[core.models.valida_documento]),
        ),
    ]
