# Generated by Django 2.1.2 on 2018-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181113_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='tipo',
            field=models.CharField(choices=[('DAN', 'Danneggiamento'), ('RIT', 'Ritardo consegna'), ('ALTRO', 'Altro')], max_length=10),
        ),
    ]
