# Generated by Django 2.1.2 on 2018-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181113_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestito',
            options={'get_latest_by': 'data_richiesta', 'verbose_name_plural': 'Prestiti'},
        ),
        migrations.AlterField(
            model_name='prestito',
            name='data_richiesta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
