# Generated by Django 2.1.2 on 2018-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181113_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autore',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='collana',
            options={'ordering': ['editore'], 'verbose_name_plural': 'Collane'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['nome'], 'permissions': (('view_dettaglio_documento', 'Accesso al dettaglio del documento'),), 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='editore',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Editori'},
        ),
        migrations.AlterModelOptions(
            name='genere',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Generi'},
        ),
        migrations.AlterModelOptions(
            name='prestito',
            options={'get_latest_by': ('data_richiesta',), 'ordering': ('data_richiesta',), 'verbose_name_plural': 'Prestiti'},
        ),
        migrations.AlterModelOptions(
            name='profilo',
            options={'ordering': ['nome', 'cognome'], 'permissions': (('sospendi_profilo', 'Sospensione dei prestiti per profilo'),), 'verbose_name_plural': 'Profili'},
        ),
        migrations.AlterModelOptions(
            name='segnalazione',
            options={'ordering': ['data'], 'verbose_name_plural': 'Segnalazioni'},
        ),
        migrations.AlterModelOptions(
            name='sottogenere',
            options={'ordering': ['padre'], 'verbose_name_plural': 'Sottogeneri'},
        ),
        migrations.AddField(
            model_name='documento',
            name='is_amministrazione',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DocumentoAmministratore',
        ),
    ]
